# This workflow will build a Java project with Maven and execute the Java classes.

name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master

 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v3
       with:
         distribution: 'adopt'
         java-version: '1.8'
     - name: Build with Maven
       run: mvn clean install
     - name: Run tests with Maven
       run: mvn test
 execute:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v3
       with:
         distribution: 'adopt'
         java-version: '1.8'
     - name: Run specific Java class
       run: java -cp target/classes techiearchive.lab.StringTest
